// <auto-generated />
using System;
using EcommerceNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceNet.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Gadgets, dispositivos y accesorios tecnológicos",
                            Nombre = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Descripcion = "Moda casual, formal y deportiva",
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Descripcion = "Muebles, decoración y electrodomésticos",
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Descripcion = "Equipamiento y ropa deportiva",
                            Nombre = "Deportes"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Descripcion = "Libros físicos y digitales",
                            Nombre = "Libros"
                        });
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOrden");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.OrdenDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenDetalles");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nombre");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Laptop 16GB RAM, SSD 512GB, RTX 4060",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Laptop",
                            Nombre = "Laptop Gaming Pro",
                            Precio = 25999.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Cancelación de ruido, 30 hrs batería",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Audifonos",
                            Nombre = "Audífonos Bluetooth",
                            Precio = 1899.50m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "IPS, 144Hz, HDR10",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Monitor",
                            Nombre = "Monitor 4K 27 pulgadas",
                            Precio = 8499.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Switches Cherry MX, retroiluminado",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Teclado",
                            Nombre = "Teclado Mecánico RGB",
                            Precio = 2199.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "100% algodón, corte regular",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Camiseta",
                            Nombre = "Camiseta Algodón Premium",
                            Precio = 399.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Mezclilla stretch, azul oscuro",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Jeans",
                            Nombre = "Jeans Slim Fit",
                            Precio = 899.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Soporte lumbar, reposabrazos ajustable",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Silla",
                            Nombre = "Silla Ergonómica de Oficina",
                            Precio = 5999.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "3 tonos de luz, dimmer táctil",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Lampara",
                            Nombre = "Lámpara LED de Escritorio",
                            Precio = 699.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Par de mancuernas con discos intercambiables",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Mancuernas",
                            Nombre = "Mancuernas Ajustables 20kg",
                            Precio = 1599.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "6mm grosor, antideslizante",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=Tapete",
                            Nombre = "Tapete de Yoga Premium",
                            Precio = 599.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 5,
                            Descripcion = "Guía para escribir código limpio y mantenible",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=CleanCode",
                            Nombre = "Clean Code — Robert C. Martin",
                            Precio = 450.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 5,
                            Descripcion = "Los 23 patrones de diseño clásicos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://placehold.co/400x300?text=DesignPatterns",
                            Nombre = "Design Patterns — Gang of Four",
                            Precio = 520.00m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ecommercenet.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Admin Tienda",
                            PasswordHash = "$2a$11$6UzHJUoBbxgCefygc7iWkO3B9TgR5j28FMElzcMhOG3tDHqYZaMLu",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Carrito", b =>
                {
                    b.HasOne("EcommerceNet.Core.Entidades.Usuario", "Usuario")
                        .WithOne("Carrito")
                        .HasForeignKey("EcommerceNet.Core.Entidades.Carrito", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.CarritoItem", b =>
                {
                    b.HasOne("EcommerceNet.Core.Entidades.Carrito", "Carrito")
                        .WithMany("Items")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceNet.Core.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Orden", b =>
                {
                    b.HasOne("EcommerceNet.Core.Entidades.Usuario", "Usuario")
                        .WithMany("Ordenes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.OrdenDetalle", b =>
                {
                    b.HasOne("EcommerceNet.Core.Entidades.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceNet.Core.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Producto", b =>
                {
                    b.HasOne("EcommerceNet.Core.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Carrito", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("EcommerceNet.Core.Entidades.Usuario", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
